// Sakurasaki All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace WeaverGameplayTags
{
	/** Input Tags **/
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleGait);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BasicAttack_Rod);
	
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InputBlocked);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InputBlocked_Movement);
	
	/** Player Tags **/
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dodge);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_BasicAttack_Rod);
	
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rod);

	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Rod);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_InterruptCurrentMontage);
	
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_Invincible);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_InAir);

	/** Enemy Tags **/


	/** Shared Tags **/
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	WEAVER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
}
