;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayCue.VFX.RockAOE",NewTagName="GameplayCue.VFX.Boss.Sevarog.Summon.AOE")
+GameplayTagRedirects=(OldTagName="GameplayCue.VFX.Boss.Sevarog.Summon.AOE",NewTagName="GameplayCue.VFX.Boss.Sevarog.Summon.RockAOE")
+GameplayTagList=(Tag="GameplayCue.SFX.MeleeHit.Stick",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Boss.Sevarog.Summon.BeamAOE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Boss.Sevarog.Summon.RockAOE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Burning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.FrostSlowed",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.HyperArmor",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.MagicShield",DevComment="")

